### ISSUE TITLE
Release the node version bump, by fixing dependencies conflict

### ISSUE THREAD

**Issue by lashchanka** [nick-invision/assert-action#34]
Hey! Thank you for fixing the issue with nodejs version bump form 12 to 16, I see that this one was probably not released yet due to this issue:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/81577230/206713889-9e12a1d8-2e9e-4029-a9df-fc0f3ee2ef17.png">

https://github.com/nick-fields/assert-action/actions/runs/3566845980/jobs/5993911228

Worth to fix this, so the change could be released

**Comment by nick-fields** [comment]
Thanks for reporting this.  I saw it then promptly forgot about it.  It's been resolved by #35
